### ISSUE TITLE
EventEmitter.prototype fails

### ISSUE THREAD

**Issue by tGrothmannFluffy** [Zolmeister/Zop#3]
Hi there,

thanks for this open source game.
I know its a couple of years old but I'm trying to run it and I get the following error:

```
Requiring external module coffeescript/register
/Users/fluffy/projects/Zop/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/socket.io/lib/socket.io.js:87:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/socket.io/index.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/karma/lib/server.js:1:72)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/node_modules/karma/lib/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/gulpfile.coffee:5:9)
    at Object.<anonymous> (/Users/fluffy/projects/Zop/gulpfile.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.loadFile (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:33:19)
    at Module.load (/Users/fluffy/projects/Zop/node_modules/coffeescript/lib/coffeescript/register.js:68:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Liftoff.handleArguments (/Users/fluffy/projects/Zop/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/Users/fluffy/projects/Zop/node_modules/liftoff/index.js:203:12)
    at module.exports (/Users/fluffy/projects/Zop/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/fluffy/projects/Zop/node_modules/liftoff/index.js:195:5)
    at /Users/fluffy/projects/Zop/node_modules/liftoff/index.js:165:9
    at /Users/fluffy/projects/Zop/node_modules/v8flags/index.js:93:14
    at FSReqWrap.oncomplete (fs.js:153:20)
```

I went back to node 9, fixed a couple of dependency warnings but this one I couldn't fix so far. Maybe you know what to do.

**Comment by tGrothmannFluffy** [comment]
All right, nvm
I got it to run on node 6 🙈
